# Site settings
title: Ion
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# repository: youknownothingg/youknownothingg.github.io
github_url: https://github.com/youknownothingg
baseurl: "/iteye" # the subpath of your site, e.g. /blog/
# url: https://youknownothingg.github.io

# Build settings
markdown: kramdown

theme: jekyll-theme-leap-day
